Repository postmanlabs/newman, pull requests merged in 2018-12, with the labels that each got.

#1808 Test requester protocol profile behavior
  npm/server.js
  npm/test-integration.js
  package-lock.json
  test/integration/protocol-profile-behavior.postman_collection.json
  test/integration/redirect-test/redirect-with-body.postman_collection.json
Labels: tests

#1815 Greenkeeper/eslint plugin jsdoc 3.12.0
  package-lock.json
  package.json
Labels: greenkeeper

#1818 Greenkeeper/eslint plugin jsdoc 3.14.0
  package-lock.json
  package.json
Labels: greenkeeper

#1836 Add integration tests for sandbox libraries
  package-lock.json
  package.json
  test/integration/sandbox-libraries.postman_collection.json
Labels: tests

#1828 Make JUnit reporter output more friendly for Azure DevOps
  lib/reporters/junit/index.js
Labels: enhancement, reporters
