Repository postmanlabs/newman, pull requests merged in 2018-05, with the labels that each got.

#1397 Added Docker push postpublish script
  .dockerignore
  docker/images/alpine33/Dockerfile
  docker/images/alpine33/README.md
  docker/images/ubuntu1404/Dockerfile
  docker/images/ubuntu1404/README.md
  npm/postpublish.sh
  package.json
  test/system/repository.test.js
Labels: docker, enhancement

#1544 chore(package): update eslint-plugin-jsdoc to version 3.7.1
  package.json
Labels: greenkeeper

#1545 chore(package): update nyc to version 11.8.0
  package.json
Labels: greenkeeper

#1546 fix(package): update postman-collection to version 3.0.10
  package.json
Labels: greenkeeper

#1528 Unique folder & request IDs in HTML report template
  lib/reporters/html/template-default.hbs
Labels: bug, reporters

#1552 Revert "Unique folder & request IDs in HTML report template"
  lib/reporters/html/template-default.hbs
Labels: reporters

#1554 Pinned applicable greenkeeper dependencies
  package.json
  test/system/repository.test.js
Labels: greenkeeper
