Repository postmanlabs/newman, pull requests merged in 2018-06, with the labels that each got.

#1566 chore(package): update nyc to version 12.0.2
  package.json
Labels: greenkeeper

#1569 chore(package): update parse-gitignore to version 0.5.1
  package.json
Labels: greenkeeper

#1551 Docker image improvements
  docker/images/alpine33/Dockerfile
  docker/images/alpine33/README.md
  docker/images/ubuntu1404/Dockerfile
  npm/postpublish.sh
  package.json
  test/system/dockerfile_rules.yml
  test/system/dockerfiles.test.js
Labels: bug, docker, enhancement

#1561 Readme updates
  CHANGELOG.yaml
  README.md
  docker/README.md
  test/system/repository.test.js
Labels: docker, documentation, enhancement, reporters

#1555 HTML reporter failures list
  lib/reporters/html/index.js
  lib/reporters/html/template-default.hbs
Labels: enhancement, feature request, reporters

#1575 Typo fixed
  examples/run-collections-in-directory.js
Labels: documentation

#1577 Unskipped auth helper integration test
  test/integration/helper.postman_collection.json
  test/integration/helper.postman_collection.skip.json
Labels: tests

#1578 CLI table the third
  .nsprc
  lib/reporters/cli/index.js
  package.json
  test/system/nsp.test.js
Labels: security

#1580 GreenKeeper ignore cli table3
  package.json
  test/system/repository.test.js
Labels: greenkeeper

#1563 Added fallback names in variable file exports
  lib/run/index.js
  test/cli/export-globals.test.js
  test/library/export-environment.test.js
  test/library/export-globals.test.js
Labels: bug

#1583 Uniform junit report timing precision
  lib/reporters/junit/index.js
  test/cli/shallow-junit-reporter.test.js
  test/library/shallow-junit-reporter.test.js
Labels: bug, reporters

#1586 Migrate System Tests to Chai
  npm/test-system.js
  package.json
  test/system/appveyor-yml.test.js
  test/system/dockerfiles.test.js
  test/system/editorconfig.test.js
  test/system/jsdoc-config.test.js
  test/system/nsp.test.js
  test/system/repository.test.js
  test/system/travis-yml.test.js
Labels: tests

#1587 Migrate Unit Tests to Chai
  npm/test-unit.js
  test/unit/cli-reporter-symbols.test.js
  test/unit/cli.test.js
  test/unit/options.test.js
  test/unit/run-summary.test.js
  test/unit/run.test.js
  test/unit/util.test.js
Labels: tests

#1591 Migrate CLI Tests to Chai
  npm/test-cli.js
  test/cli/cli-reporter-failure-details.test.js
  test/cli/cli-reporter-no-success-assertsions.test.js
  test/cli/color-tty.test.js
  test/cli/export-environment.test.js
  test/cli/export-globals.test.js
  test/cli/iteration-count.test.js
  test/cli/run-options.test.js
  test/cli/shallow-html-reporter.test.js
  test/cli/shallow-junit-reporter.test.js
  test/cli/ssl-client-cert.test.js
  test/cli/suppress-exit-code.test.js
Labels: tests

#1589 Migrate Library Tests to Chai
  npm/test-library.js
  package.json
  test/library/cookie-sanity.test.js
  test/library/export-environment.test.js
  test/library/export-globals.test.js
  test/library/folder-variants.test.js
  test/library/iteration-count.test.js
  test/library/run-options.test.js
  test/library/shallow-html-reporter.test.js
  test/library/shallow-junit-reporter.test.js
  test/library/suppress-exit-code.test.js
Labels: tests

#1593 Migrate Expect.js to Chai
  .github/CONTRIBUTING.md
  package.json
Labels: documentation, tests

#1592 documentation: Add link to the alpine image
  docker/README.md
Labels: docker, documentation

#1596 Add no-banner option for CLI reporter
  README.md
  lib/reporters/cli/index.js
  test/unit/cli.test.js
Labels: reporters

#1584 Better HTML report timeout handling
  lib/reporters/html/index.js
  lib/reporters/html/template-default.hbs
Labels: enhancement, reporters
