Repository postmanlabs/newman, pull requests merged in 2018-07, with the labels that each got.

#1611 Renamed knownReporters to knownReporterErrorMessages
  lib/run/index.js
Labels: reporters

#1576 Corrected pre-existing directory handling for exports
  README.md
  lib/run/export-file.js
  test/cli/export-environment.test.js
  test/cli/export-globals.test.js
  test/cli/shallow-html-reporter.test.js
  test/cli/shallow-junit-reporter.test.js
  test/library/export-environment.test.js
  test/library/export-globals.test.js
  test/library/shallow-html-reporter.test.js
  test/library/shallow-junit-reporter.test.js
Labels: bug, reporters

#1616 Remove inbuilt HTML reporter
  examples/reports/html-reporter-template-data.json
  examples/reports/sample-collection-report.html
  lib/reporters/html/index.js
  lib/reporters/html/template-default.hbs
  lib/run/index.js
  test/cli/shallow-html-reporter.test.js
  test/fixtures/run/failed-request.json
  test/fixtures/run/newman-report-test.json
  test/library/shallow-html-reporter.test.js
  test/unit/cli.test.js
Labels: breaking change, reporters, v4

#1612 JUnit reporter fix
  lib/reporters/junit/index.js
  test/cli/shallow-junit-reporter.test.js
  test/library/shallow-junit-reporter.test.js
Labels: bug, reporters

#1610 Drop support for v2 CLI Options
  bin/newman.js
  test/unit/cli.test.js
Labels: v4

#1618 Update README
  README.md
Labels: documentation, enhancement

#1609 Fix CSV Auto Parse
  lib/run/options.js
  lib/util.js
  test/integration/comma-test-csv/comma-test-csv.postman_collection.json
  test/integration/comma-test-csv/comma-test-csv.postman_data.csv
Labels: bug, enhancement, v4

#1623 Refactor Newman CLI
  bin/newman.js
  bin/util.js
  package.json
  test/unit/cli.test.js
Labels: cli, enhancement, tests

#1630 Updated default timeout values to Infinity :bug:
  lib/run/index.js
  package.json
Labels: breaking change, bug

#1633 Add ability to run collection via UID reference
  bin/newman.js
  lib/config/index.js
  lib/run/options.js
  lib/util.js
  package.json
  test/library/postman-api-key.test.js
  test/unit/cli.test.js
Labels: v4
