Repository postmanlabs/newman, pull requests merged in 2018-08, with the labels that each got.

#1648 Newman v4 CHANGELOG
  CHANGELOG.yaml
Labels: v4

#1649 Newman v4 Migration Guide
  MIGRATION.md
  README.md
Labels: documentation, v4

#1651 Newman v4 CHANGELOG
  CHANGELOG.yaml
Labels: v4

#1652 Updated Migration Guide
  MIGRATION.md
Labels: documentation, v4

#1653 Update `color` flag behaviour
  CHANGELOG.yaml
  MIGRATION.md
  README.md
  bin/newman.js
  lib/reporters/cli/cli-utils.js
  lib/reporters/cli/index.js
  test/cli/color-tty.test.js
  test/unit/cli.test.js
Labels: v4

#1642 Improved Docker postpublish script to account for master branch
  npm/postpublish.sh
Labels: docker

#1657 Final Newman v4 cleanup
  README.md
  bin/newman.js
  bin/util.js
  lib/index.js
  lib/version.js
  test/cli/run-options.test.js
  test/unit/cli.test.js
Labels: v4

#1643 chore(package): update parse-gitignore to version 1.0.1
  README.md
  package.json
  test/system/repository.test.js
  test/unit/cli.test.js
Labels: greenkeeper

#1660 Drop support for v1 collection format
  CHANGELOG.yaml
  MIGRATION.md
  bin/newman.js
  lib/run/options.js
  lib/util.js
  package.json
  test/integration/multi-level-folders-v1.postman_collection.json
  test/unit/run.test.js
Labels: breaking change, v4

#1663 Added v4 release notice
  README.md
Labels: documentation, v4

#1668 Readme updates
  docker/README.md
  docker/images/alpine33/README.md
  docker/images/ubuntu1404/README.md
Labels: breaking change, docker, documentation, v4

#1670 Throw error for invalid color values
  CHANGELOG.yaml
  bin/newman.js
  bin/util.js
  test/unit/cli.test.js
Labels: cli

#1684 Test: Use mapLimit to iterate integration tests
  npm/test-integration.js
Labels: tests

#1687 Add `newmanVersion` in collection run options
  README.md
  lib/run/options.js
  test/unit/options.test.js
Labels: bug

#1654 Add ability to run multiple folders
  README.md
  bin/newman.js
  bin/util.js
  lib/run/index.js
  lib/run/options.js
  test/fixtures/run/named-request.json
  test/library/folder-variants.test.js
  test/unit/cli.test.js
  test/unit/run.test.js
Labels: enhancement
