Repository postmanlabs/newman, pull requests merged in 2018-04, with the labels that each got.

#1428 Fixed help text issue
  bin/newman.js
Labels: bug

#1492 chore(package): update eslint-plugin-jsdoc to version 3.6.2
  package.json
Labels: greenkeeper, in progress

#1494 fix(package): update postman-runtime to version 7.1.5
  .nsprc
  package.json
  test/system/nsp.test.js
Labels: greenkeeper, in progress

#1496 added so --disable-unicode removes spinner when waiting for http resp…
  lib/reporters/cli/index.js
Labels: bug

#1450 feat: Add noSuccessAssertions
  README.md
  lib/reporters/cli/index.js
  test/cli/cli-reporter-no-success-assertsions.test.js
  test/unit/cli.test.js
Labels: enhancement, reporters

#1468 fix(package): update colors to version 1.2.1
  package.json
  test/cli/color-tty.test.js
Labels: greenkeeper
