Repository postmanlabs/newman, pull requests merged in 2019-02, with the labels that each got.

#1887 Added --verbose option to show detailed timing split of request
  bin/newman.js
  lib/reporters/cli/index.js
  lib/run/index.js
  lib/run/summary.js
  lib/util.js
  package-lock.json
  package.json
  test/cli/verbose.test.js
  test/unit/cli.test.js
  test/unit/util.test.js
Labels: cli, enhancement

#1874 Fixed #1871 bug where BOM marks in file were causing JSON read errors
  CHANGELOG.yaml
  README.md
  lib/config/rc-file.js
  lib/run/options.js
  lib/util.js
  package-lock.json
  package.json
  test/integration/bom-and-encoding/bom-in-collection-file.postman_collection.json
  test/integration/bom-and-encoding/bom-in-environment-file.postman_collection.json
  test/integration/bom-and-encoding/bom-in-environment-file.postman_environment.json
  test/integration/bom-and-encoding/utf16-le-encoding-in-env.postman_collection.json
  test/integration/bom-and-encoding/utf16-le-encoding-in-env.postman_environment.json
Labels: bug, enhancement

#1909 Added tests for disabled variables
  test/integration/disabled-and-duplicate-variables/disabled-and-duplicates.postman_collection.json
  test/integration/disabled-and-duplicate-variables/disabled-and-duplicates.postman_environment.json
Labels: tests
