Repository postmanlabs/newman, pull requests merged in 2019-05, with the labels that each got.

#2006 Bump dependencies to latest
  package-lock.json
  package.json
Labels: greenkeeper

#2007 Temporary fix to fetch the collection from https URL on Node v12
  lib/util.js
  test/library/postman-api-key.test.js
Labels: bug, cloud api

#1982 Secure-fs integration and related options
  .gitattributes
  CHANGELOG.yaml
  README.md
  bin/newman.js
  lib/run/index.js
  lib/run/options.js
  lib/run/secure-fs.js
  test/cli/working-directory.test.js
  test/fixtures/files/outside.json
  test/fixtures/files/work-dir/test.json
  test/fixtures/run/single-file-inside.json
  test/fixtures/run/single-file-outside.json
  test/library/working-directory.test.js
  test/unit/cli.test.js
  test/unit/options.test.js
  test/unit/secure-fs.test.js
Labels: app parity, enhancement
